---
title: "Probability concepts"
output: html_document
---

**Sample space**

* Description: A set of all the possible outcomes of an experiment.
* Notation: $\Omega$
* Type: Set
* Name of elements: Elementary outcome
* Requirements:
* Example: Outcome of two coin flips, $\{ HH, TH, HT, HH \}$

**sigma-algebra**

* Description: Defined on a sample space, consists of subsets of that set.
* Notation: $\mathcal{F}$
* Type: Collection of sets
* Name of elements: Event
* Requirements: (1) Closed under complements, (2) Closed under countable unions
* Example: $\mathcal{P}(\Omega) = \{ \emptyset, \{HH\}, \{HT\}, \dots, \{HH, TT\}, \dots, \Omega\}$

**Measurable space**

* Description: A set with a sigma-algebra defined on it.
* Notation: $(\Omega, \mathcal{F})$
* Type: Ordered pair of a set and a sigma-algebra
* Requirement: None
* Example: Ordered pair of the sample space and sigma-algebra as defined above

**Measure**

* Description: Defined on a sigma-algebra, returns the "size" of a subset of $\Omega$.
* Notation: $\mu$
* Type: Function $\mathcal{F} \rightarrow \mathbb{R}^+$
* Name of outcome: Metric
* Requirements: 
    (1) $\mu(\emptyset) = 0$, 
    (2) $\mu(A_1 \cap A_2 \cap \dots \cap A_n) = \mu(A_1) + \mu(A_2) + \dots + \mu(A_n)$ 
    if the sets are disjoint.
* Example: $\mu(A) = \frac{|A|}{|\Omega|}$

**Measure space**

* Description: A set with a sigma-algebra and a measure defined on it.
* Notation: $(\Omega, \mathcal{F}, \mu)$
* Type: Ordered triplet of a set, a sigma-algebra, and a measure.
* Requirement: None
* Example: Ordered triple of the sample space, sigma-algebra, and measure as defined above.

**Probability measure**

* Description: A special type of measure, restricted to the interval $[0,1]$ and mapping $\Omega$ to 1. Returns the probability of an event (= an element of the sigma-algebra = a subset of the sample space).
* Notation: $\mathbb{P}$
* Type: Function $\mathcal{F} \rightarrow \mathbb{R}^+$
* Name of outcome: Probability
* Requirements: 
    (1) Must be a measure
    (2) $\mathbb{P}(\Omega) = 1$
* Example: $\mathbb{P}(A) = \frac{|A|}{|\Omega|}$

**Probability space**

* Description: A set with a sigma-algebra and a probability measure defined on it.
* Notation: $(\Omega, \mathcal{F}, \mathbb{P})$
* Type: Ordered triplet of a set, a sigma-algebra, and a probability measure.
* Requirement: None
* Example: Ordered triple of the sample space, sigma-algebra, and a probability measure as defined above.

**Random variable**

* Description: A function defined on a sample space, which takes as input an elementary outcome of an experiment, and returns a real number. The purpose of this object is to translate/encode sets as numbers to make them easier to work with (e.g. defining $X$ as number of heads on two flip and hence $Y = 2 - X$ as number of tails).
* Notation: $X$
* Type: Function $\Omega \rightarrow \mathbb{R}$
* Requirements: None
* Example: "Number of heads when flipping a coin twice" = $X(HH) = 2, X(HT) = X(TH) = 1, X(TT) = 0$.

**(Cumulative) distribution function (CDF)**

* Description: An increasing function defined on a random variable, returning the probability that the random variable takes on at most that value. It does this through the following process:
    * Evaluate $X(\omega)$ for all $\omega \in \Omega$ and compare their numbers 
    with the input $x$ to $F_X$. 
    * Select all the $\omega$s that $X$ maps to numbers $\leq$ to $x$. These 
    $\omega$s form a subset of $\Omega$ (= an event = an element of the sigma-algebra).
    * Use the probability measure $\mathbb{P}$ from the probability space 
    $(\Omega, \mathcal{F}, \mathbb{P})$ to evaluate the probability of that event.
    * Return the probability.
* Notation: $F_X(x) = \mathbb{P}(X \leq x) = \mathbb{P}(\{\omega \in \Omega \mid \forall \omega \in \Omega, X(\omega) \leq x\})$
* Type: $\mathbb{R} \rightarrow [0,1]$
* Requirements: None
* Example: If $X$ is the number of heads when flipping a coin twice, then $F_X(0) = 1/4, F_X(1) = 3/4, F_X(2) = 1$. Explicitly, $F_X(1) = \mathbb{P}(X \leq 1) = \mathbb{P}(\{HT, TH, TT\}) = \frac{|\{HT, TH, TT\}|}{|\Omega|} = \frac{3}{4} = 0.75$.

**Probability (mass) function (PMF)**

* Description: A function defined on a random variable, returning the probability that the random variable takes on *exactly* that value.
* Notation: $F_X(x) = \mathbb{P}(X \leq x) = \mathbb{P}(\{\omega \in \Omega \mid \forall \omega \in \Omega, X(\omega) = x\})$
* Type: $\mathbb{R} \rightarrow [0,1]$
* Requirements: None
* Example: If $X$ is the number of heads when flipping a coin twice, then $F_X(0) = 1/4, F_X(1) = 3/4, F_X(2) = 1$.

**Probability density function (PDF)**

**Independence vs disjointedness**

* Description: Two events are independent if the probability of both of them
occurring is the product of their individual probabilities. If two events are
disjoint then they cannot both happen, so the product of their individual
probabilities must equal zero. Hence one of those probabilities must be zero.
* Independence: $A \perp B \Leftrightarrow P(A \cup B) = P(A)P(B)$
* Disjointedness: $A \cup B = \emptyset \Rightarrow P(A \cup B) = P(\emptyset) = 0 \Rightarrow P(A) = 0 \text{ or } P(B) = 0$
