---
title: Twitter Waterfall Challenge
author: EP
date: "2017-08-15"
draft: true
categories: 
  - R
tags:
  - functional programming
editor_options:
  chunk_output_type: console
---

```{r original}
wall <- c(2, 5, 1, 2, 3, 4, 7, 7, 6)

get_water_original <- function(wall) {
  len <- length(wall)
  # pre-allocate memory to make the loop more efficient
  water <- rep(0, len)
  for (i in seq_along(wall)) {
    currentHeight <- wall[i]
    maxLeftHeight <- if (i > 1) {
      max(wall[1:(i - 1)])
    } else {
      0
    }
    maxRightHeight <- if (i == len) {
      0
    } else {
      max(wall[(i + 1):len])
    }
    smallestMaxHeight <- min(maxLeftHeight, maxRightHeight)
    water[i] <- if (smallestMaxHeight - currentHeight > 0) {
      smallestMaxHeight - currentHeight
    } else {
      0
    }
  }
  water
}

get_water_original(wall)
```

```{r pkgs}
library(tidyverse)
library(forcats)
library(microbenchmark)
```

```{r get_max}
get_max <- function(x, i) {
  left  <- x[seq_len(i - 1)]
  right <- x[(i + 1):length(x)]
  list(l = max(left, 0, na.rm = TRUE),
       m = x[i],
       r = max(right, 0, na.rm = TRUE))
}
```

```{r get_depth}
get_depth <- function(i, wall) {
  x <- get_max(wall, i)
  max(min(x$l, x$r) - x$m, 0)
}
```

```{r get_water}
get_water <- function(wall) {
  map_dbl(seq_along(wall), get_depth, wall = wall)
}

get_water(wall)
```

```{r test_equality}
big_wall <- sample(1:1000, 1000, TRUE)
all(get_water_original(big_wall) == get_water(big_wall))
```

```{r benchmark}
microbenchmark(get_water(big_wall), get_water_original(big_wall))
```

```{r}
df_solution <- function(wall) {
  df <- data_frame(
    x = seq_along(wall),
    wall,
    water = get_water(wall)
  )
  gather(df, key, y, -x)
}

plot_solution <- function(df) {
  ggplot(df, aes(x + 0.5, y, fill = fct_rev(key))) +
    geom_col(position = "stack", show.legend = FALSE, width = 1) +
    scale_fill_manual(values = c("steelblue", "grey")) +
    scale_x_continuous(breaks = seq_along(wall)) +
    scale_y_continuous(breaks = seq(0, max(wall), 1)) +
    theme_void() +
    theme(
      strip.text = element_blank(),
      panel.ontop = TRUE,
      panel.grid.major.x = element_line(colour = "white", size = 0.1),
      panel.grid.major.y = element_line(colour = "white", size = 0.1),
      plot.margin = unit(rep(0, 4), "cm")
    ) +
    coord_equal()
}
```

```{r}
plot_solution(df_solution(wall))
```

```{r plots}
walls <- map_dfr(1:25, ~df_solution(sample(1:10, 10, TRUE)), 
                 .id = "draw")

plot_solution(walls) +
  facet_wrap(~draw) +
  ggtitle("Twitter Waterfall Challenge")
```
